### PR TITLE
fix namespace

### PR DESCRIPTION
**Pull request by manhg**

### CODE REVIEW

**Comment by advance512** [comment]
http://norwaytoday.info/news/russia-criticizes-norway-extradition-russian-citizen-usa/

I doubt he'll be able to merge this in, soon..

**Comment by kolypto** [comment]
@advance512 , the time has come! :))

**Comment by advance512** [comment]
@kolypto welcome back! Care sharing a bit about your adventure?

**Comment by kolypto** [comment]
@advance512 Thank you! Well, yes, it was quite an adventure. Most facts are available online, so you can follow the story. I'll share some of the things I've learned while being in prison.

First of all, I expected to see some *real criminals* there. You know, the unpleasant kind, like in the movies: large, tatooed bullies. But I was completely surprised to see that inmates are just the same sort of people you see daily in the streets. You don't have to be worse than anyone to end up in prison.
I've met different people, but I must say that they've been nice to me, and we've spent some good time (seriously) together. We talked, we shared, we played games and sports. People there don't just wait; they try to enjoy the life they have as much as they can. But it's still enormously difficult.
Norwegian prison was very, very comfortable, even better than some hotels I've seen! But make no mistake: it's still a prison, and it does not feel good at all. I've seen adult males weeping — because they miss their families. True punishment is not the lack of comfort; true punishment is the lack of love: being unable to see your loved ones. It's especially true for those who are fathers: missing your wife is one thing, but knowing that your child grows up without you is much worse.

Norway's been very kind to me, seriously: I've come to love that country more while being incarcerated. And while being there, I've had a great chance to just pause for a while and have a look at my life and ask myself some very important questions: who I am, what am I doing, and where will this kind of life lead me in the end. I've started to remember people I've hurt, words I've said that I shouldn't have. And there I came to realize that I have actually been rushing through life like a mad horse, not caring about consequences. And there, in that lonely Norwegian cell, I've come to repentance. To the decision that I don't want to live like that anymore, but I will choose a different path: the one where I spend my time and effort doing good things, and never anything that's against another person. This is "love your neighbor as you love yourself", and "do to others as you would have them do to you".

I've spent 2 years in Norway, trying to fight extradition to United States. It was scary, really scary, because I risked 25 years in prison in a faraway country, where prisons are so horrible. I've had one of the best lawyers in the country, who kindly agreed to help me for free! But it seemed that nothing worked. Until one day I finally made this decision: I have to confess to what I've done. I have to go to the United States and face my fears. May God help me. So I told my lawyer that if Norway decides to extradite me, I don't want to fight anymore. I want to go.

In the US, I've had a chance to confess to the FBI. I didn't really know anyone else in the case, because I had actually been hired as a freelancer to develop Citadel. But I confessed to what I have personally done. And I was glad to see that somehow the FBI have felt that I have come to them with complete honesty. After that, I still had another year and a half to serve.

American prison was not as comfortable as the one in Norway, but what I've learned is that comfort is not that important at all. Safety is. The next important thing is to have something meaningful to do, something that you enjoy. I've learned the art of being content with what I have, and learned to find pleasure in small things, like serving others.
I've mopped floors. I've worked in the kitchen. I've cleaned bathrooms. I've done other things — gladly, as I learned that serving others is a great pleasure: just knowing that what you do is for another person. Even if they won't appreciate.
And finally, I've spent my time learning new things. Guitar. Piano. Art. Drawing. Theology. Bilology. History. It was a good, fruitful time.
And finally, I've met some really nice people. In the US, if you stay away from drugs and gambling, if you go to church and work, then you end up in the company of people you'll love being around with. And I've mostly been around such people.

Finally, in October I was released, and immediately deported back to Russia. It was such a pleasure to see my friends again, and I've spent nearly two months just catching up with the relationships I've missed so much! I literally couldn't force myself to the laptop: it is people that I missed the most; not computers.

There was just one relationship that was different. My girlfriend, who has found someone else. It was a huge heartache that left a scar that is still in there.

@advance512 , that's the short version :)

**Pull request merged**
